[appendix]
== Perguntas para Discussão

Essas perguntas para discussão não são apenas um resumo do conteúdo em "`Filosofia do desenvolvimento do Bitcoin`", elas são feitas para incentivá-lo a pesquisar mais, então certifique-se de explorar mais.

=== Descentralização

* A descentralização é difícil. Por que passamos por todo esse esforço para fazê-la funcionar? Poderíamos optar por uma abordagem híbrida, onde algumas partes são centralizadas e outras não?
* A descentralização introduz o problema do gasto duplo, ou o problema do gasto duplo exige descentralização? Como Satoshi resolveu o problema do gasto duplo?
* Em quais aspectos o Bitcoin ainda é mais propenso à censura, e por que a censura é algo tão ruim? Existem argumentos a favor da censura?
* Afirma-se que o Bitcoin é permissão nula. Existem outros métodos de pagamento que você poderia considerar de permissão nula, desnecessária para seu uso?

=== Confiança Nula

* A confiança nula é frequentemente um espectro, não binário. Quais aspectos do Bitcoin são mais confiáveis e quais tipicamente envolvem um nível mais alto de confiança? Eles podem ser mitigados?
* Você quer executar um nó completo para poder validar completamente todas as transações. Você baixa o Bitcoin Core de https://bitcoin.org/en/download. Onde você colocou sua confiança, e onde você é totalmente sem confiança?
* É possível construir um sistema de confiança nula em cima de um sistema confiável?

=== Privacidade

* Quais são alguns benefícios importantes que um usuário obtém ao manter uma boa privacidade ao interagir com o Bitcoin? Quais são alguns benefícios altruístas para a rede?
* Como o reuso de endereços afeta sua privacidade?
* O Bitcoin usa um modelo UTXO, enquanto algumas criptomoedas alternativas usam um modelo de conta. Quais são as implicações dessa escolha na privacidade?

=== Oferta Finita

* Qual é a relação entre a oferta finita do Bitcoin e sua emissão de moedas através da transação de coinbase? Qual é a relação entre a emissão de moedas e o orçamento de segurança, e como eles estão em conflito?
* Quais parâmetros Satoshi poderia ter ajustado para alterar o limite de oferta do Bitcoin? O que mudaria se ele tivesse decidido limitar a oferta em 1 milhão? E se fosse 1 trilhão?
* Por que algumas pessoas defendem um aumento na oferta de Bitcoin? Você acha que isso vai acontecer?

=== Atualizações

* O que é o Speedy Trial e por que foi necessário para ativar o Taproot?
* Por que precisamos de um percentual tão alto de mineradores para atualizar em um softfork? Por que o limiar não é apenas 51%?

=== Pensamento Adversarial

* O que é um ataque Sybil, e por que uma rede descentralizada é tão propensa a ele?
* Por que é importante que todos os jogadores na rede Bitcoin - e não apenas os desenvolvedores - pensem de forma adversarial?

=== Código Aberto

* Apenas um punhado de mantenedores tem as permissões necessárias no GitHub para fazer merge de código no repositório https://github.com/bitcoin/bitcoin[Bitcoin Core]. Isso não é contraditório com uma rede permissionless?
* O processo de desenvolvimento de código aberto é suscetível a um ataque Sybil? Se sim, como você o enfrentaria?
* Quais são os benefícios e desvantagens de confiar em bibliotecas de código aberto de terceiros, e qual é a abordagem adotada com o Bitcoin Core?
* De que maneiras precisamos de revisão além da revisão de código? Como determinar quanto de revisão é suficiente?
* Como garantimos que sempre haverá pessoas com expertise suficientes trabalhando no Bitcoin? O que acontece quando não há, e como avaliamos sua integridade e intenções?

=== Escalabilidade

* Argumenta-se que o sharding oferece benefícios de escalabilidade ao custo de complexidade. Por que devemos ou não adotar melhorias tecnológicas porque são difíceis de entender, mesmo que pareçam tecnicamente sólidas?
* Quais são alguns exemplos de métodos de escalabilidade interna introduzidos no Bitcoin?
* Por que a escalabilidade vertical é muito mais difícil em um sistema descentralizado? E quanto à escalabilidade horizontal?
* Parece que ainda estamos longe de ter um consenso sobre como poderíamos colocar o mundo inteiro no Bitcoin. Satoshi não deveria ao menos ter pensado em um caminho para chegar lá, antes de minerar o primeiro bloco em 2009?
* Como você classificaria (vertical, horizontal, interna ou não uma técnica de escalabilidade) cada um dos seguintes: sharding, aumento de tamanho de bloco, SegWit, nós SPV, exchanges centralizadas, Lightning Network, diminuição do intervalo de bloco, Taproot, sidechains.
