[appendix]
== Feedback e contribuição

O projeto é mantido no
https://github.com/bitcoin-dev-philosophy/btcphilosophy[GitHub]. Se você tiver
qualquer melhoria, correção ou sugestão para fazer, abra uma
nova issue lá ou envie um pull request.

=== Build

O livro é escrito em https://asciidoctor.org/[Asciidoctor]. O arquivo principal
do livro é link:btcphilosophy.adoc[]. Este arquivo então
``include::`` cada capítulo como um arquivo separado.

Há também um arquivo asciidoctor separado, link:sources/sources.adoc[],
que coleta todos os recursos copiados aos quais o livro se refere. Eles
são mantidos separados para não tornar a navegação no livro muito pesada.

Antes de construir, você precisa instalar algumas dependências:

* `asciidoctor`, Veja
  https://docs.asciidoctor.org/asciidoctor/latest/install/[instruções de
  instalação]
* A extensão `asciidoctor-diagram` para `asciidoctor`. Veja
  https://docs.asciidoctor.org/diagram-extension/latest/#installation[instruções de
  instalação]
* Gnu `make`

Para construir este livro, clone o repositório GitHub:

----
$ git clone https://github.com/bitcoin-dev-philosophy/btcphilosophy.git
$ cd btcphilosophy
----

e depois construa usando qualquer um dos dois métodos abaixo

==== Manualmente usando `asciidoctor`

Use esta opção se você só quiser construir o livro casualmente e ler
o resultado final localmente. Requer apenas que o `asciidoctor` esteja
presente em seu computador. Este método não gerará QR codes para links na
margem.

----
$ asciidoctor -v btcphilosophy.adoc
----

A flag `-v` é recomendada e instrui o asciidoctor a ser verboso,
o que significa que ele mostrará referências inválidas e outros problemas. O
comando acima resultará em um arquivo `btcphilosophy.html` em seu
diretório atual que você pode visualizar em qualquer navegador, por exemplo:

----
$ brave-browser btcphilosophy.html
----

O material de origem é coletado e mantido como um livro separado
na pasta `sources`. Para construí-lo:

----
$ asciidoctor -v sources/sources.adoc
----

Isso resultará em um arquivo `sources/sources.html` que você pode abrir em
um navegador da web da mesma forma que o livro principal.

==== Usando Gnu `make`

Se você tiver acesso ao comando `make` em uma máquina Linux, você pode construir usando

----
$ make
----

Isso criará um diretório `build` e construirá tanto o livro principal
(que ficará em `build/btcphilosophy.html`) quanto o livro de fontes (que ficará em
`build/sources/sources.html`).

Se você tiver o ImageMagick instalado, o `make` reduzirá o tamanho de algumas
imagens para um download mais rápido pela web. Caso contrário, ele escreverá uma
mensagem de aviso dizendo que as imagens não serão redimensionadas.

Este método de construção é geralmente preferido, pois mantém a árvore de
origem separada dos arquivos de saída do asciidoctor, reduz o
tamanho das imagens para torná-las mais apropriadas para servir o livro
na web e produz QR codes na margem para os links.

==== Construir um PDF

Se você tiver o `asciidoctor-pdf` instalado, pode criar um PDF que
dá um resultado de melhor qualidade do que primeiro gerar html e depois
usar "`Print To PDF`" a partir disso. Crie o PDF emitindo
`asciidoctor-pdf` manualmente ou usando `make pdf`. Para emitir o
comando manualmente:

----
$ asciidoctor-pdf btcphilosophy.adoc
----

O resultado será escrito em `btcphilosophy.pdf`. Para usar `make`:

----
$ make pdf
----

O resultado será escrito em `build/btcphilosophy.pdf`.

**Este trabalho é uma tradução do original, que foi licenciado sob a Creative Commons Attribution 4.0 International (CC BY 4.0).
Foi realizada uma adaptação para incluir uma nova capa com o branding da Scalar School.
Para mais informações sobre a licença, acesse: https://creativecommons.org/licenses/by/4.0/legalcode**



