== Sobre este livro

_Bitcoin Development Philosophy_ é um guia para desenvolvedores de Bitcoin
que já entendem os conceitos básicos e processos como Proof-of-Work, construção de blocos
e o ciclo de vida das transações, e que desejam avançar adquirindo uma compreensão mais 
profunda dos trade-offs de design do Bitcoin e sua filosofia. Deve ajudar novos desenvolvedores 
a absorver as lições mais importantes de mais de uma década de desenvolvimento e debate 
público do Bitcoin, ao mesmo tempo que fornece um contexto útil para avaliar novas ideias (boas e ruins!).

Visão geral do índice:

:oldstyle: {xrefstyle}
:xrefstyle: full
<<decentralization>>::
<<trustlessness>>::
<<privacy>>::
<<finitesupply>>::
<<upgrading>>::
<<adversarialthinking>>::
<<opensource>>::
<<scaling>>::
<<whenshithitsthefan>>::
<<appendixdiscussion>>::
<<appendixbuild>>:: {empty}

:xrefstyle: {oldstyle}

Seu feedback e contribuições são muito bem-vindos! Instruções para
construção e contribuição podem ser encontradas em <<appendixbuild>>.

=== O que esperar?

Como afirmado acima, este é um guia prático para desenvolvedores de Bitcoin. 
No entanto, o Bitcoin é um assunto amplo e complexo e não poderíamos cobrir todos 
os seus aspectos aqui. Com este livro, esperamos discutir os recursos necessários 
para iniciar sua atividade de desenvolvimento, bem como permitir que você explore 
isso por conta própria.

Existem muitas pessoas envolvidas no Bitcoin; como algumas delas têm opiniões opostas, 
aqui você pode encontrar recursos que expressam ideias contraditórias. No entanto, 
sempre tentamos nos ater ao domínio dos fatos, onde as opiniões não importam.

=== Quem escreveu isto?

O autor principal deste livro é Kalle Rosenbaum, e Linnéa Rosenbaum contribuiu como coautora. 
Este trabalho foi encomendado e financiado por https://learning.chaincode.com/[Chaincode Labs], 
um centro de desenvolvimento que oferece programas educacionais para desenvolvedores que desejam 
aprender sobre o desenvolvimento do Bitcoin.

Kalle é o autor de https://rosenbaum.se/book/[_Grokking Bitcoin_] (Manning Publications) e é 
um desenvolvedor de software experiente. Ele trabalha profissionalmente com desenvolvimento 
relacionado ao Bitcoin desde 2015.

Linnéa tem um Ph.D. em Sistemas Eletrônicos. Ela é a tradutora sueca de 
https://konsensus.network/product/lilla-boken-om-bitcoin/[_The Little Bitcoin Book_] 
e co-tradutora de https://konsensus.network/product/sverige-bitcoinstandarden/[_The Bitcoin Standard_]. 
Ela também faz parte do conselho da Associação Sueca de Bitcoin. Seu histórico é em desenvolvimento 
de firmware, com uma mudança recente para desenvolvimento de software.

=== Como isso está organizado?

O livro está dividido em capítulos, cada um cobrindo um tópico fundamental dentro do Bitcoin. 
Cada capítulo guia você pelas informações relevantes relacionadas ao foco do capítulo, 
com a adição de links e códigos QR que levarão você a artigos ou vídeos que recomendamos 
ler ou assistir. O material reportado foi escrito por indivíduos que estudam o desenvolvimento 
do Bitcoin há muito tempo.

Os links referem-se a recursos externos em plataformas que não podemos controlar. 
Portanto, salvamos os artigos vinculados localmente neste repositório, junto com as 
informações de onde foram copiados e quando. Os recursos estão coletados em 
link:sources/sources.html[um documento separado] (`sources/sources.adoc`) e organizados 
pelo capítulo ao qual estão vinculados. Os links encontrados nos capítulos referem-se às 
fontes originais, que devem ser encontradas online, mas caso você não tenha conexão à internet, 
os links apareçam mortos ou as informações pareçam severamente alteradas, você pode ler o conteúdo 
localmente em vez disso.
